### PR TITLE
multinomial dirichlet, variance decomposition, forecast validation plots and yeast forecast

### PR DESCRIPTION
**Pull request by colinaverill**
This is a huge 2 month pull request. I apologize!

1. Built multinomial dirichlet fitting and forecast functions.
2. Wrote code to execute variance decomposition.
3. Built forecast validation plot scripts.
4. Added a new set of models for yeast (yeast a single-celled fungi). yeast/non-yeast may be analogous to r vs. k selected organisms for fungi.

### CODE REVIEW

**Review by mdietze — APPROVED** [review]

**Comment by mdietze** [comment]
@colinaverill this branch has file conflicts that need to be resolved before I can merge

```
16S/data_construction/prior_16S_bahram/2._process_seqs_dada2.r
16S/data_construction/prior_16S_bahram/qsub_scripts/2q_process_seqs_dada2.txt
16S/data_construction/prior_16S_bahram/qsub_scripts/3q_assign_taxonomy_rdp.txt
```

**Comment by colinaverill** [comment]
Gotcha. This branch can be totally rejected, as Zoey has taken over development of the 16S branch. Trying to figure out how to do that on my end.

**Comment by colinaverill** [comment]
Looks like I don't have permission to resolve these conflicts? Screen grab below:
image

**Comment by colinaverill** [comment]
Wait, i fixed it myself. I get it now. hooray for github.

**Pull request merged**
